import { create } from "zustand";

export interface Email {
  id: string;
  from: string;
  fromEmail: string;
  subject: string;
  body: string;
  date: string;
  read: boolean;
  priority: "high" | "medium" | "low";
  category: "work" | "personal" | "updates" | "promotions";
}

export interface CalendarEvent {
  id: string;
  title: string;
  start: string; // ISO
  end: string;   // ISO
  location?: string;
  attendees?: string[];
  description?: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

export type CielStatus = "idle" | "thinking" | "speaking" | "listening" | "error";

interface CielState {
  // auth state
  user: { name: string; email: string } | null;
  login: (name: string, email: string) => void;
  logout: () => void;

  // view state
  activeTab: "overview" | "inbox" | "calendar" | "chat" | "settings";
  setActiveTab: (tab: "overview" | "inbox" | "calendar" | "chat" | "settings") => void;

  // mock email data
  emails: Email[];
  selectedEmailIndex: number | null;
  searchQuery: string;
  setEmails: (emails: Email[]) => void;
  setSelectedEmailIndex: (index: number | null) => void;
  setSearchQuery: (query: string) => void;
  markAsRead: (id: string) => void;
  archiveEmail: (id: string) => void;
  addEmail: (email: Email) => void;

  // mock calendar data
  calendarEvents: CalendarEvent[];
  setCalendarEvents: (events: CalendarEvent[]) => void;
  addCalendarEvent: (event: CalendarEvent) => void;

  // chat state
  chatMessages: ChatMessage[];
  addChatMessage: (message: Omit<ChatMessage, "id" | "timestamp">) => void;
  clearChat: () => void;

  // 3D face animation state
  cielStatus: CielStatus;
  setCielStatus: (status: CielStatus) => void;
  currentVolume: number; // voice volume level (0-1)
  setCurrentVolume: (vol: number) => void;
}

// initial mock emails
const initialEmails: Email[] = [
  {
    id: "1",
    from: "Corsair Developer Relations",
    fromEmail: "dev@corsair.dev",
    subject: "Welcome to Corsair! Your Google integrations are active.",
    body: "Hi there!\n\nWe noticed you connected your Gmail and Google Calendar accounts to Ciel. You are now fully configured to use our MCP server and Webhooks in real-time.\n\nLet us know if you need help wiring up advanced search or custom filtering!\n\nBest,\nThe Corsair Team",
    date: "10:45 AM",
    read: false,
    priority: "high",
    category: "work",
  },
  {
    id: "2",
    from: "Rimuru Tempest",
    fromEmail: "rimuru@tempest.gov",
    subject: "Status report on the magical barrier coordinates",
    body: "Ciel,\n\nI need you to run a quick check on the barrier coordinates. Souei reports some weird magicule fluctuations near the eastern borders. Also, let's reschedule our meeting with King Gazel. Let me know what times work best next Thursday.\n\nThanks!",
    date: "9:15 AM",
    read: false,
    priority: "high",
    category: "work",
  },
  {
    id: "3",
    from: "Veldora Tempest",
    fromEmail: "veldora@tempest.gov",
    subject: "Urgently need new manga recommendations!",
    body: "Ciel! Where are the updates to my sacred texts (manga)? I finished the last volumes Rimuru brought. Send them over right away, or I shall be forced to unleash my aura in the cave again!",
    date: "Yesterday",
    read: true,
    priority: "medium",
    category: "personal",
  },
  {
    id: "4",
    from: "GitHub Notifications",
    fromEmail: "noreply@github.com",
    subject: "[GitHub] Security Alert: 3 dependencies require update in ciel-mcp",
    body: "Hello @0nlyjs,\n\nWe found 3 vulnerable dependencies in your ciel-mcp repository. Please review the security alerts and pull requests generated by Dependabot.",
    date: "Yesterday",
    read: true,
    priority: "low",
    category: "updates",
  },
  {
    id: "5",
    from: "Google Calendar",
    fromEmail: "calendar-notification@google.com",
    subject: "Notification: Hackathon Pitch @ Fri Jun 12 2pm",
    body: "You have an upcoming event:\n\nHackathon Pitch\nWhen: Friday, Jun 12, 2026, 2:00 PM - 2:30 PM\nWhere: Discord Hackathon Stage\n\nAttendees: dev@corsair.dev, mistjs@ciel.app",
    date: "2 days ago",
    read: true,
    priority: "high",
    category: "updates",
  },
];

// initial calendar mock data
const initialEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Ciel Hackathon Pitch",
    start: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split("T")[0] + "T14:00:00",
    end: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split("T")[0] + "T14:30:00",
    location: "Discord Hackathon Stage",
    attendees: ["dev@corsair.dev", "mistjs@ciel.app"],
    description: "Pitching our superhuman clone Ciel powered by Corsair integrations and reactive 3D speech models.",
  },
  {
    id: "e2",
    title: "Sync with Rimuru",
    start: new Date().toISOString().split("T")[0] + "T16:00:00",
    end: new Date().toISOString().split("T")[0] + "T17:00:00",
    location: "Tempest Meeting Hall",
    attendees: ["rimuru@tempest.gov"],
    description: "Discussing magicule barrier calibrations and scheduling.",
  },
];

export const useCielStore = create<CielState>((set) => ({
  // auth state
  user: null,
  login: (name, email) => set({ user: { name, email } }),
  logout: () => set({ user: null, activeTab: "overview" }),

  // view state
  activeTab: "overview",
  setActiveTab: (tab) => set({ activeTab: tab }),

  // email data
  emails: initialEmails,
  selectedEmailIndex: 0,
  searchQuery: "",
  setEmails: (emails) => set({ emails, selectedEmailIndex: emails.length > 0 ? 0 : null }),
  setSelectedEmailIndex: (index) => set({ selectedEmailIndex: index }),
  setSearchQuery: (query) => set({ searchQuery: query }),
  markAsRead: (id) =>
    set((state) => ({
      emails: state.emails.map((email) =>
        email.id === id ? { ...email, read: true } : email
      ),
    })),
  archiveEmail: (id) =>
    set((state) => {
      const filtered = state.emails.filter((email) => email.id !== id);
      return {
        emails: filtered,
        selectedEmailIndex:
          filtered.length > 0
            ? Math.min(state.selectedEmailIndex ?? 0, filtered.length - 1)
            : null,
      };
    }),
  addEmail: (email) =>
    set((state) => ({
      emails: [email, ...state.emails],
      selectedEmailIndex: 0,
    })),

  // calendar data
  calendarEvents: initialEvents,
  setCalendarEvents: (events) => set({ calendarEvents: events }),
  addCalendarEvent: (event) =>
    set((state) => ({
      calendarEvents: [...state.calendarEvents, event].sort(
        (a, b) => new Date(a.start).getTime() - new Date(b.start).getTime()
      ),
    })),

  // chat data
  chatMessages: [
    {
      id: "init",
      role: "assistant",
      content: "Hello, I am Ciel, your sentient AI workspace mind. I have established synchronization with your Gmail and Google Calendar. How may I assist you with your inbox or schedule today?",
      timestamp: new Date(),
    },
  ],
  addChatMessage: (msg) =>
    set((state) => ({
      chatMessages: [
        ...state.chatMessages,
        {
          id: Math.random().toString(),
          role: msg.role,
          content: msg.content,
          timestamp: new Date(),
        },
      ],
    })),
  clearChat: () => set({ chatMessages: [] }),

  // 3d face animation state
  cielStatus: "idle",
  setCielStatus: (status) => set({ cielStatus: status }),
  currentVolume: 0,
  setCurrentVolume: (vol) => set({ currentVolume: vol }),
}));
